todo/urls.py
from django.urls import path

from todo.views import (TaskListView, TagListView, TaskCreateView,
                        TaskUpdateView, TagCreateView, TagUpdateView,
                        TaskDeleteView, TagDeleteView, TaskToggleDoneView,)

urlpatterns = [
        path("", TaskListView.as_view(), name="tasks_list"),
        path("create/", TaskCreateView.as_view(), name="task_create"),
        path("update/<int:pk>", TaskUpdateView.as_view(), name="task_update"),
        path("tags/", TagListView.as_view(), name="tags_list"),
        path("tags/create/", TagCreateView.as_view(), name="tag_create"),
        path("tags/update/<int:pk>/", TagUpdateView.as_view(), name="tag_update"),
        path("<int:pk>/delete/", TaskDeleteView.as_view(), name="task_delete"),
        path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag_delete"),
        path("<int:pk>/toggle/", TaskToggleDoneView.as_view(), name="task_toggle_done"),

]

app_name = "todo"

todolist/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
# from django.contrib import admin
from django.urls import path, include

urlpatterns = [
        # path("admin/", admin.site.urls),
        path("", include("todo.urls", namespace="todo")),
] + debug_toolbar_urls()

todo/models.py
from django.db import models



class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.CharField(max_length=255)
    created = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True, blank=True)
    done = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, related_name="tasks", blank=True)

    class Meta:
        ordering = ["done", "-created"]

    def __str__(self):
        return self.content




todo/views.py
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views import generic, View

from todo.models import Task, Tag


class TaskListView(generic.ListView):
    model = Task
    queryset = Task.objects.prefetch_related("tags").order_by("done", "-created")
    paginate_by = 5

class TaskCreateView(generic.CreateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("todo:tasks_list")
    template_name = "todo/task_form.html"


class TaskUpdateView(generic.UpdateView):
    model = Task
    template_name = "todo/task_form.html"
    fields = "__all__"
    success_url = reverse_lazy("todo:tasks_list")


class TaskDeleteView(generic.DeleteView):
    model = Task
    template_name = "todo/task_confirm_delete.html"
    success_url = reverse_lazy("todo:tasks_list")


class TagListView(generic.ListView):
    model = Tag
    paginate_by = 5


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo:tags_list")
    template_name = "todo/tag_form.html"


class TagUpdateView(generic.UpdateView):
    model = Tag
    template_name = "todo/tag_form.html"
    fields = "__all__"
    success_url = reverse_lazy("todo:tags_list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    template_name = "todo/tag_confirm_delete.html"
    success_url = reverse_lazy("todo:tags_list")


class TaskToggleDoneView(View):
    def post(self, request, pk):
        task = get_object_or_404(Task, pk=pk)
        task.done = not task.done
        task.save()
        return redirect("todo:tasks_list")

templates/base.html
<!doctype html>
<html lang="en">
<head>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  {% block title %}<title>Todo List</title> {% endblock %}
 <style>

    body {
    padding: 20px;
  }

  </style>
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-1">
        {% block sidebar %}
          {% include "includes/sidebar.html" %}
        {% endblock %}
      </div>

      <div class="col-sm-11">
        {% block content %}
        {% endblock %}

        {% block pagination %}
          {% include "includes/pagination.html" %}
        {% endblock %}
      </div>

    </div>
  </div>
</body>
</html>

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
  {% if page_obj.has_previous %}
    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Prev</a></li>
    {% endif %}
  <li class="page-item active"><span class="page-link">{{page_onj.number}} of {{ paginator.num_pages }}></span></li>
  {% if page_obj.has_next %}
    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
  {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'todo:tasks_list' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'todo:tags_list' %}">Tags</a></li>
</ul>

templates/todo/tag_confirm_delete.html
{% extends "base.html" %}
{% block content %}
  <h1>Delete Tag</h1>
  <p>Are you sure you want to delete {{ tag.name }}</p>
  <form action="" method="post">
  {% csrf_token %}
  <input type="submit" value="Yes, Delete" class="btn btn-danger" />
  </form>
{% endblock %}

templates/todo/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Tag</h1>
  <form action="" method="POST" novalidate>
    {% csrf_token %}
  {{ form|crispy }}
  <input class="btn btn-primary" type="submit" value="Create Task" />
  </form>
{% endblock %}

templates/todo/tag_list.html
{% extends "base.html" %}
{% block content %}
  <h1>Tags</h1>
  <a style="float:right;" class="btn btn-primary" href="{% url 'todo:tag_create' %}">Add Tag</a>
  <table class="table">
  <thead>
  <tr>
      <th>Name</th>
   <th>Update</th>
  <th>Delete</th>
  </tr>
  </thead>
  <tbody>
  {% for tag in tag_list %}
    <tr>
    <td>{{ tag.name }}</td>
    <td><a class="btn btn-secondary" href="{% url 'todo:tag_update' tag.id %}">Update</a></td>
    <td><a class="btn btn-secondary" href="{% url 'todo:tag_delete' tag.id %}">Delete</a></td>
    </tr>
  {% endfor %}</table>
{% endblock %}

templates/todo/task_confirm_delete.html
{% extends "base.html" %}
{% block content %}
  <h1>Delete Task</h1>
  <p>Are you sure you want to delete {{ task.content }}</p>
  <form action="" method="post">
  {% csrf_token %}
  <input type="submit" value="Yes, Delete" class="btn btn-danger" />
  </form>
{% endblock %}

templates/todo/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Task</h1>
  <form action="" method="POST" novalidate>
    {% csrf_token %}
  {{ form|crispy }}
  <input class="btn btn-primary" type="submit" value="Create Task" />
  </form>
{% endblock %}

templates/todo/task_list.html
{% extends "base.html" %}
{% block title %}
  <title>TODO list</title>
{% endblock %}

{% block content %}
  <h1>TODO List</h1>
  <a style="float:right;" class="btn btn-primary" href="{% url 'todo:task_create' %}">Add Task</a>
  <br>
  <div class="mt-4">
    {% for task in task_list %}
      <div class="d-flex justify-content-between align-items-center border-bottom py-2">
        <div>
          <h5 class="mb-1">
            <strong>{{ task.content }}</strong>
            {% if task.done %}
              <span class="text-success">Done</span>
            {% else %}
              <span class="text-danger">Not done</span>
            {% endif %}
          </h5>
          <p class="mb-1">
            Created: {{ task.created|date:"F j, Y, g:i a" }}
            {% if task.deadline %}
              <span class="text-danger">Deadline: {{ task.deadline|date:"F j, Y, g:i a" }}</span>
            {% endif %}
          </p>
          <p class="text-muted mb-0">
            Tags:
            {% for tag in task.tags.all %}
              {{ tag.name }}{% if not forloop.last %}, {% endif %}
            {% empty %}
              no tags
            {% endfor %}
            <a href="{% url 'todo:task_update' task.id %}">Update</a> |
            <a href="{% url 'todo:task_delete' task.id %}">Delete</a>
          </p>
        </div>

        <div>
          {% if not task.done %}
            <form method="post" action="{% url 'todo:task_toggle_done' task.id %}">
              {% csrf_token %}
            <button type="submit" class="btn btn-success">Complete</button>
            </form>
          {% else %}
            <form method="post" action="{% url 'todo:task_toggle_done' task.id %}">
              {% csrf_token %}
            <button type="submit" class="btn btn-secondary">Undo</button>
            </form>
          {% endif %}
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}